/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package piano;

import org.junit.Test;
import static org.junit.Assert.*;

public class BlockTest {

    @Test
    public void constructure() {
        assertNotNull(new Block());
    }
    
    @Test
    public void blockTest() {
        Block b = new Block();
        assertFalse(b.isActive()); // test default block
        b.click();
        assertTrue(b.isActive()); // test click on a de-actived block
        b.click();
        assertFalse(b.isActive()); // test click on a actived block
    }
    
}

//gradle run
//gradle test
//gradle jacocoTestReport
